# Generated by Django 5.2.9 on 2026-01-02 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0004_alter_city_image_alt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('area_name', models.CharField(blank=True, max_length=120)),
                ('cover_image', models.ImageField(blank=True, upload_to='developments/')),
                ('cover_image_alt', models.CharField(blank=True, help_text='Describe the image for screen readers.', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developments', to='cities.city')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['city'], name='development_city_id_8f27d2_idx'), models.Index(fields=['is_active'], name='development_is_acti_4dc9f5_idx')],
            },
        ),
    ]
