# Generated by Django 5.2.9 on 2026-01-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='development',
            name='address_line',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='development',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='development',
            name='operator_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='development',
            name='operator_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='development',
            name='postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='development',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='development',
            name='tenancy_options',
            field=models.CharField(blank=True, choices=[('long-term', 'Long-term'), ('flexible', 'Flexible'), ('short-stay-available', 'Short-stay available')], max_length=30),
        ),
        migrations.AddField(
            model_name='development',
            name='website_url',
            field=models.URLField(blank=True),
        ),
    ]
