# Generated by Django 5.2.9 on 2026-01-08 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0002_development_address_line_development_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='developments/')),
                ('alt_text', models.CharField(blank=True, help_text='Describe the image for screen readers.', max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('development', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='developments.development')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
