# Generated by Django 5.2.9 on 2026-01-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0003_developmentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='development',
            name='bills_included',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('some', 'Some bills included'), ('all', 'All bills included')], max_length=20),
        ),
        migrations.AddField(
            model_name='development',
            name='furnishing',
            field=models.CharField(blank=True, choices=[('furnished', 'Furnished'), ('part-furnished', 'Part-furnished'), ('unfurnished', 'Unfurnished'), ('flexible', 'Flexible')], max_length=30),
        ),
        migrations.AddField(
            model_name='development',
            name='minimum_term_months',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum tenancy term in months (e.g. 6, 12, etc).', null=True),
        ),
        migrations.AddField(
            model_name='development',
            name='number_of_homes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='development',
            name='pet_policy',
            field=models.CharField(blank=True, choices=[('pets-allowed', 'Pets allowed'), ('pets-considered', 'Pets considered'), ('no-pets', 'No pets')], max_length=30),
        ),
        migrations.AddField(
            model_name='development',
            name='property_type',
            field=models.CharField(blank=True, choices=[('apartments', 'Apartments'), ('studio', 'Studio'), ('house', 'House')], max_length=30),
        ),
        migrations.AddField(
            model_name='development',
            name='tenancy_length',
            field=models.PositiveIntegerField(blank=True, help_text='Typical/standard tenancy length in months', null=True),
        ),
    ]
