# Generated by Django 5.2.9 on 2026-01-09 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0005_amenity_development_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='development',
            name='deposit_from',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='development',
            name='pricing_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='development',
            name='rent_from_pcm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrooms', models.PositiveSmallIntegerField(choices=[(0, 'Studio'), (1, '1-bedroom'), (2, '2-bedroom'), (3, '3-bedroom'), (4, '4-bedroom')])),
                ('rent_from_pcm', models.PositiveIntegerField(blank=True, null=True)),
                ('rent_to_pcm', models.PositiveIntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('development', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_types', to='developments.development')),
            ],
            options={
                'ordering': ['bedrooms'],
                'indexes': [models.Index(fields=['development'], name='development_develop_e5fc7b_idx'), models.Index(fields=['development', 'bedrooms'], name='development_develop_dda05f_idx')],
                'constraints': [models.UniqueConstraint(fields=('development', 'bedrooms'), name='unique_unit_type_per_development')],
            },
        ),
    ]
