# Generated by Django 5.2.9 on 2026-01-15 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0006_development_deposit_from_development_pricing_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in-progress', 'In progress'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('development', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='developments.development')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['development'], name='development_develop_821a22_idx'), models.Index(fields=['status'], name='development_status_9bd1f7_idx'), models.Index(fields=['created_at'], name='development_created_ce4b82_idx')],
            },
        ),
    ]
