# Generated by Django 5.2.9 on 2026-01-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0007_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='forwarded_at',
            field=models.DateTimeField(blank=True, help_text='When the enquiry was forwarded.', null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='forwarded_to_email',
            field=models.EmailField(blank=True, help_text='Email address the enquiry was forwarded to.', max_length=254),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='move_timeframe',
            field=models.CharField(blank=True, choices=[('asap', 'ASAP'), ('1-3-months', '1-3 months'), ('3-6-months', '3-6 months'), ('6-plus-months', '6+ months'), ('just-browsing', 'Just browsing')], help_text='When the renter is looking to move.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['move_timeframe'], name='development_move_ti_728434_idx'),
        ),
    ]
