# Generated by Django 5.2.9 on 2026-01-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0008_enquiry_forwarded_at_enquiry_forwarded_to_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='development',
            name='summary',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
