# Generated by Django 5.2.9 on 2026-01-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0009_alter_development_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='development',
            name='summary',
            field=models.CharField(blank=True, help_text='Max 160 characters.', max_length=160),
        ),
    ]
