# Generated by Django 5.2.9 on 2025-12-31 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Describe the image for. screen readers.', max_length=120),
        ),
    ]
