# Generated by Django 5.2.9 on 2025-12-31 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_city_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['show_on_homepage'], name='cities_city_show_on_fd07b0_idx'),
        ),
    ]
