# Generated by Django 5.2.9 on 2026-01-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_city_show_on_homepage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Describe the image for screen readers.', max_length=120),
        ),
    ]
